// ID
const SET_ID = 'SET_ID';

// ORGANIZATION
const ADD_CONTACTS = 'ADD_CONTACTS';
const REMOVE_CONTACTS = 'REMOVE_CONTACTS';
const ADD_EMAILS = 'ADD_EMAILS';
const REMOVE_EMAILS = 'REMOVE_EMAILS';
const SELECT_GROUP = 'SELECT_GROUP';
const FUNDCODE_CHANGE = 'FUNDCODE_CHANGE';

// EVENT
const EVENT_NAME_CHANGE = 'EVENT_NAME_CHANGE';
const EVENT_DATE_CHANGE = 'EVENT_DATE_CHANGE';
const START_TIME_CHANGE = 'START_TIME_CHANGE';
const END_TIME_CHANGE = 'END_TIME_CHANGE';
const UNDERGRAD_CHANGE = 'UNDERGRAD_CHANGE';
const GRADUATE_CHANGE = 'GRADUATE_CHANGE';
const EVENT_LOCATION_CHANGE = 'EVENT_LOCATION_CHANGE';
const EVENT_AUDIENCE_CHANGE = 'EVENT_AUDIENCE_CHANGE';

// PROGRAMMING
const CELLS_CHANGE = 'CELLS_CHANGE';
const ROW_CHANGE = 'ROW_CHANGE';

module.exports = {
  SET_ID,
  ADD_CONTACTS,
  REMOVE_CONTACTS,
  ADD_EMAILS,
  REMOVE_EMAILS,
  SELECT_GROUP,
  FUNDCODE_CHANGE,
  EVENT_NAME_CHANGE,
  EVENT_DATE_CHANGE,
  START_TIME_CHANGE,
  END_TIME_CHANGE,
  UNDERGRAD_CHANGE,
  GRADUATE_CHANGE,
  EVENT_LOCATION_CHANGE,
  EVENT_AUDIENCE_CHANGE,
  CELLS_CHANGE,
  ROW_CHANGE
};
