// ORGANIZATION ACTION TYPES
export const ADD_CONTACTS = 'ADD_CONTACTS';
export const REMOVE_CONTACTS = 'REMOVE_CONTACTS';
export const ADD_EMAILS = 'ADD_EMAILS';
export const REMOVE_EMAILS = 'REMOVE_EMAILS';
export const SELECT_GROUP = 'SELECT_GROUP';
export const FUNDCODE_INPUT_CHANGE = 'FUNDCODE_INPUT_CHANGE';
