// ORGANIZATION ACTION TYPES
export const ADD_CONTACTS = 'ADD_CONTACTS';
export const REMOVE_CONTACTS = 'REMOVE_CONTACTS';
export const ADD_EMAILS = 'ADD_EMAILS';
export const REMOVE_EMAILS = 'REMOVE_EMAILS';
export const SELECT_GROUP = 'SELECT_GROUP';
export const FUNDCODE_CHANGE = 'FUNDCODE_CHANGE';
export const EVENT_NAME_CHANGE = 'EVENT_NAME_CHANGE';
export const EVENT_DATE_CHANGE = 'EVENT_DATE_CHANGE';
export const START_TIME_CHANGE = 'START_TIME_CHANGE';
export const END_TIME_CHANGE = 'END_TIME_CHANGE';
